bookshorts/models.py
from bookshorts import db


#책 정보 저장
class BookInfo(db.Model): #db.Model = 모든 모델의 기본 class
    id = db.Column(db.Integer, primary_key=True) #primary_key를 통해 배타성을 확보
    title = db.Column(db.String(32), nullable=False) #빈값을 허용하고 싶지 않다면 nullable = False로 설정함.
    author = db.Column(db.String(32), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False) #생성 시간
    answer = db.Column(db.String(400), nullable=True) #나중에 저장


#회원가입
class Fcuser(db.Model): 
    __tablename__ = 'fcuser'   #테이블 이름 : fcuser : 주로 사용자 정보를 나타내는 클래스
    id = db.Column(db.Integer, primary_key = True)   #id를 프라이머리키로 설정
    password = db.Column(db.String(64))     #패스워드를 받아올 문자열길이 
    userid = db.Column(db.String(32))       #이하 위와 동일
    username = db.Column(db.String(8))

bookshorts/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # Initialize ORM
    db.init_app(app)
    migrate.init_app(app, db)  # Migrate handles database migrations

    from bookshorts import models  # Ensure your models are imported so they are registered with SQLAlchemy
    from .views import main_views, history_views, login_views, summarize_views

    app.register_blueprint(login_views.bp)
    app.register_blueprint(main_views.bp)
    app.register_blueprint(history_views.bp)
    app.register_blueprint(summarize_views.bp)

    with app.app_context():
        db.create_all()  # Create tables for all models (useful for initial setup, but usually handled by migrations)

    return app

if __name__ == "__main__":
    app = create_app()
    app.run(host='127.0.0.1', port=5000, debug=True)

bookshorts/views/history_views.py
#### 요약한 책을 볼 수 있는 뷰 ####


from flask import Flask, Blueprint, render_template, url_for
from ..models import BookInfo
import json



bp = Blueprint('history', __name__, url_prefix='/history')

# 요약 리스트 보여주기
@bp.route('/', methods=['GET'])
def history():
    book_list = BookInfo.query.order_by(BookInfo.create_date.desc())
    return render_template('book_list/book_list.html', book_list=book_list)

# 요약 리스트 클릭시 답변 상세 보기
@bp.route('/summarized/<int:id>', methods=['GET'])
def title(id):
    book = BookInfo.query.get_or_404(id)
    # answer 필드가 JSON 문자열인지 확인하고 리스트로 변환합니다.
    try:
        answer_list = json.loads(book.answer) if book.answer else []
    except json.JSONDecodeError:
        answer_list = []
    return render_template('book_list/summarized.html', book=book, answer_list=answer_list)

bookshorts/views/login_views.py
#### 회원가입, 로그인을 처리하는 뷰 ####

from flask import Blueprint, url_for, render_template, request, session
from werkzeug.security import check_password_hash
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash
from ..models import Fcuser
from bookshorts import db


bp = Blueprint('login', __name__, url_prefix='/login')


#회원가입(login/register)
@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        #회원정보 생성 (register html -> python 객체)
        username = request.form.get('username')
        userid = request.form.get('userid') 
        password = request.form.get('password')
        re_password = request.form.get('re_password')
        print(password) # 들어오나 확인해볼 수 있다. 

        if not (username and userid and password and re_password) :
            message = "빈칸을 모두 입력해주세요"
            return render_template('register.html', message=message)
        elif password != re_password:
            message = "비밀번호가 일치하지 않습니다."
            return render_template('register.html', message=message)
        else: #모두 입력이 정상적으로 되었다면 밑에명령실행(DB에 입력됨) (python 객체 -> Database)
            try:
                fcuser = Fcuser()
                fcuser.username = username
                fcuser.password = generate_password_hash(password, method='pbkdf2:sha256')  # Use pbkdf2:sha256
                fcuser.userid = userid
                db.session.add(fcuser)
                db.session.commit()
                message = "회원가입 완료"
                return render_template('login.html', message=message)
            except Exception as e:
                db.session.rollback()  # Rollback the session in case of error
                return f"An error occurred: {e}"
        

#로그인(login/)
@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    if request.method == 'POST':
        error=None
        userid = request.form.get('userid')
        password = request.form.get('password')
        print(userid, password)
        if not (userid and password):
            message = "아이디와 비밀번호를 입력해주세요"
            return render_template('login.html', message=message)
        else:
            fcuser = Fcuser.query.filter_by(userid=userid).first()
            if fcuser is None:
                message = "사용자가 존재하지 않습니다"
                return render_template('login.html', message=message)
            elif check_password_hash(fcuser.password, password):
                session['userid'] = userid
                return redirect(url_for('/.bookinfo'))
            else:
                message = "아이디와 비밀번호를 확인해주세요"
                return render_template('login.html', message=message)

bookshorts/views/main_views.py
#### 첫화면 ####

from flask import Blueprint, render_template, request, redirect, url_for
from bookshorts import db
from ..models import Fcuser
from werkzeug.security import generate_password_hash

#p45 main, __name__, url_prefix를 설정해 줘야 한다고 함. 처음 두 개 뭔지 나중에 확인할 것
bp = Blueprint('main', __name__, url_prefix='/')

# 바로 로그인 뷰로 redirect함
@bp.route('/')
def login_first():
    return render_template('login.html')

bookshorts/views/summarize_views.py
#### 책 입력 뷰 --> 책 요약 화면 html ####


from flask import Blueprint, render_template, request
from ..models import BookInfo
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv  
import os
from bookshorts import db
import re
import json

load_dotenv()
openai_api_key=os.getenv('OPENAI_API_KEY')

bp = Blueprint('/', __name__, url_prefix='/')


#요약하기 버튼을 누르면 동작하는 것

@bp.route('/answer', methods=['GET', 'POST'])
def bookinfo():
    if request.method == 'GET':
        return render_template('index.html')
    if request.method == 'POST':
        #회원정보 생성 (register html -> python 객체)
        title = request.form.get('title') 
        author = request.form.get('author')
        print(title, author) # 들어오나 확인해볼 수 있다. 

        if (title and author):
         #모두 입력이 정상적으로 되었다면 밑에명령실행(DB에 입력됨) (python 객체 -> Database)
            bookinfo = BookInfo()         
            bookinfo.title = title          
            bookinfo.author = author
            bookinfo.create_date = datetime.now()      
            db.session.add(bookinfo)
            db.session.commit()
        
        book_info = f"{author}의 {title}"
        print(book_info)

        openai = OpenAI(api_key=openai_api_key)
        response = openai.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
            {"role": "system", "content": 
            f'''Don't say; just do
            "당신은 세계 최고의 도서 요약 전문가입니다. 
            저자가 작성한 책의 제목과 저자를 알려주면 당신은 책의 핵심 인사이트를 저자에게 요약합니다. 
            {book_info}의 책의 핵심 포인트와 인사이트를 5가지로 요약해주세요. 무조건 한국어로 대답하세요."
            , "형식: {book_info} 핵심 인사이트 요약: 1. 2. 3. 4. 5."
            '''},
            ]   
        )
        content = response.choices[0].message.content
        insights = re.split(r'\d+\.', content) # 숫자와 점을 기준으로 분리합니다.
        insights = [insight.strip() for insight in insights if insight.strip() != ''] # 빈 문자열을 제거하고 양쪽 공백을 제거합니다.
        bookinfo.answer = json.dumps(insights) #리스트를 JSON 문자열로 변환하여 저장해야 합니다. 그리고 데이터를 가져올 때는 json.loads()를 사용해 다시 리스트로 변환할 수 있습니다.
        db.session.add(bookinfo)
        db.session.commit()
        return render_template('summarize.html', 
                               book_info=book_info, 
                               insights=insights) #author, title 정보를 summarize.html로 넘겨줌

bookshorts/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">    
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %} - bookshorts</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

bookshorts/templates/book_list/book_list.html
{% extends 'base.html' %}

{% block title %}도서 목록{% endblock %}

{% block content %}
<nav>
    <a class="nav-link" href="{{ url_for('history.history') }}">히스토리 보기</a>
    <a class="nav-link" href="{{ url_for('/.bookinfo') }}">책 요약하기</a>
</nav>
{% if book_list %}
    <h1>도서 목록</h1>
    <ul class="book-list">
        {% for book in book_list %}
            <li class="book-item"><a href="/history/summarized/{{ book.id }}">{{ book.title }} - {{ book.author }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>등록된 도서가 없습니다.</p>
{% endif %}
{% endblock %}

bookshorts/templates/book_list/summarized.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <a class="nav-link" href="{{ url_for('history.history') }}">히스토리 보기</a>
    <a class="nav-link" href="{{ url_for('/.bookinfo') }}">책 요약하기</a>
</nav>
<h1>{{ book.title }} - {{ book.author }}</h1>

<div>
    <ol>
    {% for answer in answer_list %}
            <li>{{ answer }}</li>
        {% endfor %}
    </ol>
</div>
</script>
{% endblock %}

bookshorts/templates/index.html
{% extends 'base.html' %}
    {% block title %} bookshorts {% endblock %}
    {% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
    {% endblock %}
    {% block content %}
    <nav>
        <a class="nav-link" href="{{ url_for('history.history') }}">히스토리 보기</a>
        <a class="nav-link" href="{{ url_for('/.bookinfo') }}">책 요약하기</a>
    </nav>
    <div class="container">
        <div class="hero">
            <h1 class="title">bookshorts</h1>
            <h3 class="subtitle">1분에 책 한 권 읽기</h3>
        </div>

        <!-- 시작 화면 (intro) -->
        <div id="intro" class="intro-container">
            <form method="post" action="{{ url_for('/.bookinfo') }}" onsubmit="start()">
                <h1>bookshorts에 오신 것을 환영합니다! 요약하고 싶은 책을 적어주세요.</h1>
                <div class="input-section">
                    <label for="title">제목</label>
                    <input id="title" name="title">
                </div>
                <div class="input-section">
                    <label for="author">저자</label>
                    <input id="author" name="author">
                </div>
                <div class="button-container">
                    <button type="submit">요약하기</button>
                </div>
            </form>
            </div>
          <!-- Chat 버튼 눌렀을 때  -->
    
        <!-- kakao ad -->
        <div class="kakao-ad">
            <ins class="kakao_ad_area" style="display:none;" data-ad-unit="DAN-KbdwsZ8O86UWMOWU" data-ad-width="320"
                data-ad-height="100"></ins>
            <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
        </div>

        <script>

            // Searh 관련 function
            function start() {
                const title = document.getElementById('title').value;
                const author = document.getElementById('author').value;

                if (title === '') {
                    alert('책 제목을 적어주세요!');
                    return;
                }
                if (author === '') {
                    alert('저자의 이름을 적어주세요!');
                    return;
                }    
            }
        </script>
    </div>
    {% endblock %}

bookshorts/templates/login.html
{% extends "base.html" %}
{% block title %}로그인{% endblock %}
{% block content %}
    <div class="container">
        <div class="login-form">
            <h1 style="text-align: center;">로그인 페이지</h1>
            {% if error %}
                <p>{{ error }}</p>
            {% endif %}
            <form method="POST", action="{{ url_for('login.login') }}" class="input-section">
                <label for="userid">아이디</label>
                <input type="text" id="userid" name="userid" required>
                <label for="password">비밀번호</label>
                <input type="password" id="password" name="password" required>
                <div class="button-container">
                    <button type="submit" class="button">로그인하기</button>
                </div>
            </form>
            <a href="{{ url_for('login.register') }}" class="login-link">회원가입하기</a>
        </div>
    </div>
    <script>
        {% if message %}
            alert("{{ message }}");
        {% endif %}
    </script>
{% endblock %}

bookshorts/templates/register.html
{% extends "base.html" %}
{% block title %}회원가입{% endblock %}
{% block content %}
<div class="container">
    <div class="login-form">
        <form action="{{ url_for('login.register') }}" method="post">
            <div class="input-section">
                <label for="username">이름</label>
                <input type="text" name="username" id="username" class="input-section input">
            </div>
            <div class="input-section">
                <label for="userid">아이디</label>
                <input type="text" name="userid" id="userid" class="input-section input">
            </div>
            <div class="input-section">
                <label for="password">비밀번호</label>
                <input type="password" name="password" id="password" class="input-section input">
            </div>
            <div class="input-section">
                <label for="password2">비밀번호 확인</label>
                <input type="password" name="re_password" id="re_password" class="input-section input">
            </div>
            <div class="button-container">
                <button type="submit" class="button-container button" style="text-align: center;">회원가입하기</button>
            </div>
        </form>
    </div>
</div>
<script>
    {% if message %}
        alert("{{ message }}");
    {% endif %}
</script>
{% endblock %}

bookshorts/templates/summarize.html
{% extends 'base.html' %}
{% block title %} {{ book_info }} 요약 {% endblock %}
{% block content %}
<nav>
    <a class="nav-link" href="{{ url_for('history.history') }}">히스토리 보기</a>
    <a class="nav-link" href="{{ url_for('/.bookinfo') }}">책 요약하기</a>
</nav>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
            integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="shortcut icon" href="favicon.ico">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
      <style>
         body {
        background: #007BFF;  /* fallback for old browsers */
        background: -webkit-linear-gradient(to right, #0062E6, #33AEFF);  /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to right, #0062E6, #33AEFF); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        color: #fff;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        font-family: 'Poppins', sans-serif;
    }
        </style>
    <div id="chat" class="chat-container">
        <div class="chat-box">
            <form method="post" action="/summarize">            
                <div class="chat-message assistant-welcome">
                <p class="assistant">
                        {% for insight in insights %}
                            <li>{{ insight }}</li>
                        {% endfor %}
                </p>
                </div>
        </div>
    </div>
        
{% endblock %}